{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.data.claimName | default (printf "%s-data" (include "uos.fullname" .)) }}
  labels:
    {{- include "uos.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
{{- end }}
